CREATE TABLE MERCADO ( 
    MERCADOID NUMBER PRIMARY KEY, 
    NOMEMERCADO VARCHAR2(80) NOT NULL, 
    ENDERECO VARCHAR2(80) NOT NULL 
); 

CREATE SEQUENCE MERCADO_PROJETO_ID_SEQ;  
 

CREATE TABLE PRODUTO ( 
    PRODUTOID NUMBER PRIMARY KEY, 
    NOME VARCHAR2(80) NOT NULL, 
    PRECO NUMBER(7,2) NOT NULL,
    MERCADOID NUMBER NOT NULL,
        FOREIGN KEY (MERCADOID)
        REFERENCES MERCADO(MERCADOID)
); 

CREATE SEQUENCE PRODUTO_PROJETO_ID_SEQ;